name: Release

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Build
        run: |
          python -m pip install poetry
          poetry install
          poetry build

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
